# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mooonika

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mounikaregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e7b876b969db43a0a7fcf061b80026ab }}
        password: ${{ secrets.AzureAppService_ContainerPassword_19e84458b50644d1a918e75745e5e0f5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mounikaregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e7b876b969db43a0a7fcf061b80026ab }}/mounikaregistry/mounikaimg:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mooonika'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ff852c52029b46f797d002dc0ec95360 }}
        images: 'mounikaregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e7b876b969db43a0a7fcf061b80026ab }}/mounikaregistry/mounikaimg:${{ github.sha }}'